### PR TITLE
Use mysql2 instead of mysql in Joomla3 importer

### PR DESCRIPTION
**Pull request by ienev**
Use and require mysql2 gem instead of mysql for the Joomla3 importer. Change similar to the one for the Joomla importer - #255.

### CODE REVIEW

**Comment by ienev** [comment]
AFAIK the `mysql` [gem](https://rubygems.org/gems/mysql/) won't compile with ruby 2.4  due to the Fixnum and Bignum unification:

```shell
compiling mysql.c
mysql.c: In function ‘stmt_bind_result’:
mysql.c:1320:74: error: ‘rb_cFixnum’ undeclared (first use in this function)
  else if (argv[i] == rb_cNumeric || argv[i] == rb_cInteger || argv[i] == rb_cFixnum)
                                                                          ^
mysql.c:1320:74: note: each undeclared identifier is reported only once for each function it appears in
mysql.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1: warning: unrecognized command line option ‘-Wno-tautological-compare’
Makefile:241: recipe for target 'mysql.o' failed
make: *** [mysql.o] Error 1

make failed, exit code 2
``` 

The maintainer has deprecated development of the gem and no new version has been released for the past 4 years.

Since there are other importers using `mysql`, may be it is worth applying this change to them too? The gem is also required as a development dependency in the [gemspec](https://github.com/jekyll/jekyll-import/blob/master/jekyll-import.gemspec#L51). This seems like a something that needs to be discussed though (probably in a separate Issue) as it only affects ruby 2.4.

**Comment by parkr** [comment]
> may be it is worth applying this change to them too? 

That sounds great! Want to upgrade all of them in this PR? 😍

**Comment by ienev** [comment]
> Want to upgrade all of them in this PR?

Sure. What about the `.gemspec`? I guess requiring `mysql` won't be needed anymore?

**Comment by parkr** [comment]
> Sure. What about the .gemspec? I guess requiring mysql won't be needed anymore?

Yes! You can replace that with mysql2 or just remove it.

**Comment by parkr** [comment]
@jekyllbot: merge
